apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
spec:
  serviceAccountName: vault-agent-example
  containers:
    - name: devwebapp
      image: burtlo/devwebapp-ruby:k8s
      env:
        - name: VAULT_ADDR
          value: "https://vault.vault.svc.cluster.local:8200"
        - name: VAULT_CACERT
          value: "/etc/vault/ca/ca.pem"
      volumeMounts:
        - name: vault-ca-cert
          mountPath: /etc/vault/ca
          readOnly: true
  volumes:
    - name: vault-ca-cert
      secret:
        secretName: vault-ca-cert